---
title: "data wrangling SS"
author: "M.Kinneen"
date: "2023-03-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
```

## Sheet codes
1 = catches
2 = indices
3 = age comps
4 = weight at age 
5 = maturity
6 = params
7 = Selectivity 
8 = Aging error

## Catches


```{r catches}
catch_raw<- readxl::read_xlsx("./Provided_Example/SuperSimpleParamsAndData.xlsx", sheet = 1)
#_Catch data: yr, seas, fleet, catch, catch_se
#            -999    1     1     0       0.01

n_rows<- nrow(catch_raw)
yr<- c(-999,seq(from = min(catch_raw$Year),to = max(catch_raw$Year), by = 1), -9999) # add years
seas<- c(1,rep(1, n_rows),0) #seasons
fleet <- c(1,rep(1, n_rows),0) #fleets
catch<- c(0,catch_raw$Catch,0) #catch
catch_se<- c(0.01,rep(0.01, n_rows),0) #standard error

catch_formatted<- data.frame(cbind(yr,seas,fleet,catch,catch_se))
print(catch_formatted, row.names = FALSE)
```

## Indices

`You can also embed plots, for example:
```{r indices}

indices_raw<- readxl::read_xlsx("./Provided_Example/SuperSimpleParamsAndData.xlsx", sheet = 2)

## Data

#Examples
#_yr month fleet obs stderr
# 1977 7 2 339689 0.3 #_ SURVEY1

n_rows<-nrow(indices_raw) # define number of rows

yr<- indices_raw$Year # define years
month <- indices_raw$Month # months of surveys
fleets <- rep(2,length(yr)) #specify fleets
obs<- indices_raw$Observation
stderr <- indices_raw$Error

ind_data<- cbind(yr,month,fleets,obs,stderr)

#Terminator
ind_term<- cbind(-9999,1,1,1,1)

#combine data
indices_formatted<- data.frame(rbind(ind_data,ind_term))

print(indices_formatted, row.names = FALSE)
```

## Age comp

```{r agecomp}

age_raw<- readxl::read_xlsx("./Provided_Example/SuperSimpleParamsAndData.xlsx", sheet = 3)

age_comp_data<-as.data.frame(age_raw)


age_comp_data$Fleet <- ifelse(age_comp_data$Fleet == "fishery",1,2) # Recode fleet
age_comp_data$Sex <- ifelse(age_comp_data$Sex == "both",3,-99) #Recode sex


#term
term<- c(-9999, rep(0, ncol(age_comp_data)-1))

# fromatted data
age_comp_formatted<-data.frame(rbind(age_comp_data, term))



print(age_comp_formatted, row.names= FALSE)

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
